#!/bin/bash
#by morfeus
Gpio_pin=31

#--- uncomment if u want to read from comand line the pin number to use from cubian documentation
#--- http://docs.cubieboard.org/products/a10_cubieboard/expansion_ports
#read Gpio_pin

echo "START"
#--- Initialisation : export , direction 
#--- export the pin
echo $Gpio_pin > /sys/class/gpio/export
sleep 1
#--- look for pin name when exported 
gpio=( $(ls /sys/class/gpio | grep $Gpio_pin ) )
#echo "nr: " ${#gpio[@]}
echo "U should connect to ground and pin" $Gpio_pin "on cubian documentation" 
echo "Pin name:" ${gpio[@]} 

#--- set as output pin
echo out > /sys/class/gpio/${gpio[@]}/direction
#cat /sys/class/gpio/${gpio[@]}/value

#--- led test without blinking - led on 
#echo 1 > /sys/class/gpio/${gpio[@]}/value

for (( i = 1 ; i <= 15 ; i++ )); do
  echo "blink" $i
  #--- led on
  echo 1 > /sys/class/gpio/${gpio[@]}/value
  sleep 1 
  #--- led off    
  echo 0 > /sys/class/gpio/${gpio[@]}/value
  sleep 1
done

#--- clean up
#--- unexport the pin
echo $Gpio_pin > /sys/class/gpio/unexport
echo "FINISH"
